/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.uniska.pbo2.p03.komponen.gui;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FormPendaftaran extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPendaftaran.class.getName());

    /**
     * Creates new form FormPendaftaran
     */
    public FormPendaftaran() {
        initComponents();
        
        // Kode tambahan ditulis setelah initComponents(), di luar blok abu-abu buatan NetBeans
        namaField.putClientProperty("JTextField.placeholderText", "Nama lengkap");
        npmField.putClientProperty("JTextField.placeholderText", "Contoh: 2410010001");
        getRootPane().setDefaultButton(daftarButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kelaminGroup = new javax.swing.ButtonGroup();
        namaLabel = new javax.swing.JLabel();
        npmLabel = new javax.swing.JLabel();
        prodiLabel = new javax.swing.JLabel();
        jeniskelaminLabel = new javax.swing.JLabel();
        minatLabel = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();
        npmField = new javax.swing.JTextField();
        prodiCombo = new javax.swing.JComboBox<>();
        lakiRadio = new javax.swing.JRadioButton();
        perempuanRadio = new javax.swing.JRadioButton();
        javacheck = new javax.swing.JCheckBox();
        pythoncheck = new javax.swing.JCheckBox();
        webcheck = new javax.swing.JCheckBox();
        temaToggle = new javax.swing.JToggleButton();
        daftarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Pendaftaran Workshop");

        namaLabel.setText("NAMA");
        namaLabel.setName("namaLabel"); // NOI18N

        npmLabel.setText("NPM");
        npmLabel.setName("npmLabel"); // NOI18N

        prodiLabel.setText("PROGRAM STUDI");
        prodiLabel.setName("prodiLabel"); // NOI18N

        jeniskelaminLabel.setText("JENIS KELAMIN");
        jeniskelaminLabel.setName("JenisKelaminLabel"); // NOI18N

        minatLabel.setText("MINAT");
        minatLabel.setName("MinatLabel"); // NOI18N

        namaField.setName("namaField"); // NOI18N

        npmField.setName("npmField"); // NOI18N

        prodiCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TEKNIK INFORMATIKA", "SISTEM INFORMASI", "MANAJEMEN INFORMATIKA" }));
        prodiCombo.setName("prodiCombo"); // NOI18N

        kelaminGroup.add(lakiRadio);
        lakiRadio.setSelected(true);
        lakiRadio.setLabel("LAKI-LAKI\n");
        lakiRadio.setName("Laki-lakiRadio"); // NOI18N

        kelaminGroup.add(perempuanRadio);
        perempuanRadio.setText("PEREMPUAN ");
        perempuanRadio.setName("PerempuanRadio"); // NOI18N

        javacheck.setText("Java");
        javacheck.addActionListener(this::javacheckActionPerformed);

        pythoncheck.setText("python");

        webcheck.setText("web");

        temaToggle.setText("Mode Gelap");
        temaToggle.addActionListener(this::temaToggleActionPerformed);

        daftarButton.setText("DAFTAR");
        daftarButton.addActionListener(this::daftarButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minatLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jeniskelaminLabel)
                            .addComponent(prodiLabel)
                            .addComponent(npmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prodiCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lakiRadio)
                                .addGap(18, 18, 18)
                                .addComponent(perempuanRadio))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(temaToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(daftarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(javacheck, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pythoncheck, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(webcheck, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(npmField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                .addComponent(namaField, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel)
                    .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(npmLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodiLabel)
                    .addComponent(prodiCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perempuanRadio)
                    .addComponent(lakiRadio)
                    .addComponent(jeniskelaminLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minatLabel)
                    .addComponent(javacheck)
                    .addComponent(pythoncheck)
                    .addComponent(webcheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daftarButton)
                    .addComponent(temaToggle))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void javacheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_javacheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_javacheckActionPerformed

    private void temaToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temaToggleActionPerformed


    gantiTema(temaToggle.isSelected());        // TODO add your handling code here:
    }//GEN-LAST:event_temaToggleActionPerformed

    private void daftarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarButtonActionPerformed


    tampilkanRingkasan();
    }//GEN-LAST:event_daftarButtonActionPerformed
    private void tampilkanRingkasan() {
    String jenisKelamin = lakiRadio.isSelected() ? "Laki-laki" : "Perempuan";
    List<String> minat = new ArrayList<>();
    for (JCheckBox cb : List.of(javacheck, pythoncheck, webcheck)) {
    if (cb.isSelected()) {
    minat.add(cb.getText());
}
}
    String pesan = "Nama: " + namaField.getText()
    + "\nNPM: " + npmField.getText()
    + "\nProgram Studi: " + prodiCombo.getSelectedItem()
    + "\nJenis Kelamin: " + jenisKelamin
    + "\nMinat: " + (minat.isEmpty() ? "-" : String.join(", ", minat));
    JOptionPane.showMessageDialog(this, pesan, "Data Pendaftaran",
    JOptionPane.INFORMATION_MESSAGE);
}
private void gantiTema(boolean gelap) {
if (gelap) {
FlatDarkLaf.setup();
} else {
FlatLightLaf.setup();
}
FlatLaf.updateUI(); // terapkan tema baru ke semua jendela yang terbuka
temaToggle.setText(gelap ? "Mode Terang" : "Mode Gelap");
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPendaftaran().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton daftarButton;
    private javax.swing.JCheckBox javacheck;
    private javax.swing.JLabel jeniskelaminLabel;
    private javax.swing.ButtonGroup kelaminGroup;
    private javax.swing.JRadioButton lakiRadio;
    private javax.swing.JLabel minatLabel;
    private javax.swing.JTextField namaField;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField npmField;
    private javax.swing.JLabel npmLabel;
    private javax.swing.JRadioButton perempuanRadio;
    private javax.swing.JComboBox<String> prodiCombo;
    private javax.swing.JLabel prodiLabel;
    private javax.swing.JCheckBox pythoncheck;
    private javax.swing.JToggleButton temaToggle;
    private javax.swing.JCheckBox webcheck;
    // End of variables declaration//GEN-END:variables
}
