/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.uniska.pbo2.p03.komponen.gui;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FormPemesananTiketTravel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPemesananTiketTravel.class.getName());

    /**
     * Creates new form FormPemesananTiketTravel
     */
    public FormPemesananTiketTravel() {
        initComponents();
        // Kode tambahan ditulis setelah initComponents(), di luar blok abu-abu buatan NetBeans
        namaField.putClientProperty("JTextField.placeholderText", "Nama Sesuai Ktp");
        NoHpField.putClientProperty("JTextField.placeholderText", "Contoh: 08xxxxxxx ");
        getRootPane().setDefaultButton(pesanButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KelasGroup = new javax.swing.ButtonGroup();
        namaField = new javax.swing.JTextField();
        NoHpField = new javax.swing.JTextField();
        KotaCombo = new javax.swing.JComboBox<>();
        EkonomiRadio = new javax.swing.JRadioButton();
        BagasiCheck = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        catatanArea = new javax.swing.JTextArea();
        pesanButton = new javax.swing.JButton();
        tematoggle = new javax.swing.JToggleButton();
        NamaLabel = new javax.swing.JLabel();
        NoHpLabel = new javax.swing.JLabel();
        KotaLabel = new javax.swing.JLabel();
        KelasLabel = new javax.swing.JLabel();
        BisnisRadio = new javax.swing.JRadioButton();
        EksekutifRadio = new javax.swing.JRadioButton();
        FasilitasLabel = new javax.swing.JLabel();
        MakanCheck = new javax.swing.JCheckBox();
        AsuransiCheck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        namaField.addActionListener(this::namaFieldActionPerformed);

        KotaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BANJARBARU", "MARTAPURA", "PALANGKARAYA", "SAMARINDA", "BALIKPAPAN" }));

        KelasGroup.add(EkonomiRadio);
        EkonomiRadio.setSelected(true);
        EkonomiRadio.setText("Ekonomi");
        EkonomiRadio.addActionListener(this::EkonomiRadioActionPerformed);

        BagasiCheck.setText("Bagasi");

        catatanArea.setColumns(20);
        catatanArea.setRows(3);
        jScrollPane1.setViewportView(catatanArea);

        pesanButton.setText("PESAN");
        pesanButton.addActionListener(this::pesanButtonActionPerformed);

        tematoggle.setText("Mode Gelap");
        tematoggle.addActionListener(this::tematoggleActionPerformed);

        NamaLabel.setText("Nama Pesanan");

        NoHpLabel.setText("No Hp");

        KotaLabel.setText("Kota Tujuan");

        KelasLabel.setText("Kelas");

        KelasGroup.add(BisnisRadio);
        BisnisRadio.setText("Bisnis");

        KelasGroup.add(EksekutifRadio);
        EksekutifRadio.setText("Eksekutif");

        FasilitasLabel.setText("Fasilitas Tambahan");

        MakanCheck.setText("Makan");
        MakanCheck.addActionListener(this::MakanCheckActionPerformed);

        AsuransiCheck.setText("Asuransi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FasilitasLabel)
                                .addGap(18, 18, 18)
                                .addComponent(BagasiCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NamaLabel)
                                    .addComponent(NoHpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(namaField, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(NoHpField))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EksekutifRadio)
                            .addComponent(AsuransiCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(KotaLabel)
                                    .addComponent(KelasLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(EkonomiRadio)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(MakanCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BisnisRadio)))
                                    .addComponent(KotaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tematoggle, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(pesanButton)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamaLabel)
                    .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NoHpLabel)
                    .addComponent(NoHpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KotaLabel)
                    .addComponent(KotaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KelasLabel)
                    .addComponent(EkonomiRadio)
                    .addComponent(BisnisRadio)
                    .addComponent(EksekutifRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FasilitasLabel)
                    .addComponent(BagasiCheck)
                    .addComponent(MakanCheck)
                    .addComponent(AsuransiCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesanButton)
                    .addComponent(tematoggle))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaFieldActionPerformed

    private void EkonomiRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EkonomiRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EkonomiRadioActionPerformed

    private void tematoggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tematoggleActionPerformed
        // TODO add your handling code here:
         gantiTema(tematoggle.isSelected());
    }//GEN-LAST:event_tematoggleActionPerformed

    private void pesanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanButtonActionPerformed
        // TODO add your handling code here:
        tampilkanRingkasan();
    }//GEN-LAST:event_pesanButtonActionPerformed

    private void tampilkanRingkasan() {
    String kelas = EkonomiRadio.isSelected() ? "Ekonomi"
            : BisnisRadio.isSelected() ? "Bisnis"
            : "Eksekutif";

    List<String> fasilitas = new ArrayList<>();

    for (JCheckBox cb : List.of(BagasiCheck, MakanCheck, AsuransiCheck)) {
        if (cb.isSelected()) {
            fasilitas.add(cb.getText());
        }
    }

    String pesan = "Nama Pemesan: " + namaField.getText()
            + "\nNomor HP: " + NoHpField.getText()
            + "\nKota Tujuan: " + KotaCombo.getSelectedItem()
            + "\nKelas: " + kelas
            + "\nFasilitas: " + (fasilitas.isEmpty()
                    ? "-" : String.join(", ", fasilitas))
            + "\nCatatan: " + catatanArea.getText();

    JOptionPane.showMessageDialog(
            this,
            pesan,
            "Ringkasan Pemesanan",
            JOptionPane.INFORMATION_MESSAGE
    );
    }
    
    private void gantiTema(boolean gelap) {
    if (gelap) {
        FlatDarkLaf.setup();
    } else {
        FlatLightLaf.setup();
    }

    FlatLaf.updateUI();
    tematoggle.setText(gelap ? "Mode Terang" : "Mode Gelap");
    }
    
    private void MakanCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakanCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MakanCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPemesananTiketTravel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AsuransiCheck;
    private javax.swing.JCheckBox BagasiCheck;
    private javax.swing.JRadioButton BisnisRadio;
    private javax.swing.JRadioButton EkonomiRadio;
    private javax.swing.JRadioButton EksekutifRadio;
    private javax.swing.JLabel FasilitasLabel;
    private javax.swing.ButtonGroup KelasGroup;
    private javax.swing.JLabel KelasLabel;
    private javax.swing.JComboBox<String> KotaCombo;
    private javax.swing.JLabel KotaLabel;
    private javax.swing.JCheckBox MakanCheck;
    private javax.swing.JLabel NamaLabel;
    private javax.swing.JTextField NoHpField;
    private javax.swing.JLabel NoHpLabel;
    private javax.swing.JTextArea catatanArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namaField;
    private javax.swing.JButton pesanButton;
    private javax.swing.JToggleButton tematoggle;
    // End of variables declaration//GEN-END:variables
}
